-- 회차 댓글(평면). 작성자·회차 참조 + 본문.
create table comments (
    id         bigint        generated by default as identity primary key,
    user_id    bigint        not null references users (id),
    episode_id bigint        not null references episodes (id),
    content    varchar(1000) not null,
    created_at timestamptz   not null,
    updated_at timestamptz   not null
);

create index idx_comments_episode_id on comments (episode_id);
