-- 회차 북마크. user-episode 멱등(유니크) — read_logs/episode_likes 구조를 복제한다.
create table bookmarks (
    id         bigint      generated by default as identity primary key,
    user_id    bigint      not null references users (id),
    episode_id bigint      not null references episodes (id),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_bookmark_user_episode unique (user_id, episode_id)
);

create index idx_bookmarks_user_id on bookmarks (user_id);
