-- 문의(Inquiry). 독자/작가/관리자 모두 작성, 관리자가 답변·상태 관리.
-- 다중 이미지는 episode_images 구조를 복제(inquiry_images, FK cascade).
create table inquiries (
    id         bigint        generated by default as identity primary key,
    user_id    bigint        not null references users (id),
    type       varchar(20)   not null,
    title      varchar(255)  not null,
    content    varchar(5000) not null,
    answer     varchar(2000),
    status     varchar(20)   not null default 'PENDING',
    created_at timestamptz   not null,
    updated_at timestamptz   not null
);

create index idx_inquiries_user_id on inquiries (user_id);
create index idx_inquiries_status on inquiries (status);

create table inquiry_images (
    id         bigint       generated by default as identity primary key,
    inquiry_id bigint       not null references inquiries (id) on delete cascade,
    sort_order int          not null,
    path       varchar(500) not null,
    width      int          not null,
    height     int          not null
);

create index idx_inquiry_images_inquiry_id on inquiry_images (inquiry_id);
