-- 프로필 확장 + 법적 동의 + 작가 전환 신청. 기존 사용자는 avatar/bio NULL.
alter table users add column avatar_key varchar(500);
alter table users add column bio        varchar(500);

-- 법적 동의(현재상태 스냅샷 — user별 type당 1행, version/agreed_at으로 감사).
create table user_consents (
    id           bigint       generated by default as identity primary key,
    user_id      bigint       not null references users (id) on delete cascade,
    consent_type varchar(30)  not null,
    version      int          not null,
    agreed       boolean      not null,
    agreed_at    timestamptz,
    created_at   timestamptz  not null,
    updated_at   timestamptz  not null,
    constraint uq_user_consent unique (user_id, consent_type)
);
create index idx_user_consents_user on user_consents (user_id);

-- 작가 전환 신청(심사). status: PENDING → APPROVED/REJECTED.
create table creator_requests (
    id             bigint        generated by default as identity primary key,
    user_id        bigint        not null references users (id) on delete cascade,
    status         varchar(20)   not null default 'PENDING',
    request_reason varchar(1000) not null,
    admin_note     varchar(1000),
    reviewed_by    bigint,
    reviewed_at    timestamptz,
    created_at     timestamptz   not null,
    updated_at     timestamptz   not null
);
create index idx_creator_requests_status on creator_requests (status);
create index idx_creator_requests_user on creator_requests (user_id);
