-- 팔로우(사용자 간, 주로 독자→작가). follower가 following을 팔로우. 멱등(유니크).
create table follows (
    id           bigint      generated by default as identity primary key,
    follower_id  bigint      not null references users (id) on delete cascade,
    following_id bigint      not null references users (id) on delete cascade,
    created_at   timestamptz not null,
    updated_at   timestamptz not null,
    constraint uq_follow_pair unique (follower_id, following_id)
);

create index idx_follows_following on follows (following_id);
create index idx_follows_follower on follows (follower_id);
