-- 커뮤니티: 게시글 + 이미지(다중) + 추천 + 댓글(대댓글 1-depth). 블라인드 플래그 포함.
create table posts (
    id         bigint        generated by default as identity primary key,
    author_id  bigint        not null references users (id) on delete cascade,
    category   varchar(20)   not null,
    title      varchar(255)  not null,
    content    varchar(5000) not null,
    like_count int           not null default 0,
    blinded    boolean       not null default false,
    created_at timestamptz   not null,
    updated_at timestamptz   not null
);
create index idx_posts_created on posts (created_at desc);
create index idx_posts_category on posts (category);

create table post_images (
    id         bigint       generated by default as identity primary key,
    post_id    bigint       not null references posts (id) on delete cascade,
    sort_order int          not null,
    path       varchar(500) not null,
    width      int          not null,
    height     int          not null
);
create index idx_post_images_post on post_images (post_id);

create table post_likes (
    id         bigint      generated by default as identity primary key,
    user_id    bigint      not null references users (id) on delete cascade,
    post_id    bigint      not null references posts (id) on delete cascade,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_post_like unique (user_id, post_id)
);
create index idx_post_likes_post on post_likes (post_id);

create table post_comments (
    id         bigint        generated by default as identity primary key,
    post_id    bigint        not null references posts (id) on delete cascade,
    author_id  bigint        not null references users (id) on delete cascade,
    parent_id  bigint        references post_comments (id) on delete cascade,
    content    varchar(1000) not null,
    blinded    boolean       not null default false,
    created_at timestamptz   not null,
    updated_at timestamptz   not null
);
create index idx_post_comments_post on post_comments (post_id);
create index idx_post_comments_parent on post_comments (parent_id);
