-- 신고(범용 폴리모픽 대상). 한 신고자가 한 대상을 1번만(유니크). 자동 블라인드는 앱이 집계해 처리.
create table reports (
    id          bigint        generated by default as identity primary key,
    reporter_id bigint        not null references users (id) on delete cascade,
    target_type varchar(20)   not null,   -- POST/COMMENT/USER/SERIES/EPISODE
    target_id   bigint        not null,
    reason      varchar(20)   not null,   -- SPAM/ABUSE/SEXUAL/COPYRIGHT/ETC
    detail      varchar(1000),
    status      varchar(20)   not null default 'PENDING',
    handled_by  bigint,
    handled_at  timestamptz,
    created_at  timestamptz   not null,
    updated_at  timestamptz   not null,
    constraint uq_report_once unique (reporter_id, target_type, target_id)
);
create index idx_reports_status on reports (status);
create index idx_reports_target on reports (target_type, target_id);
