create table users (
    id         bigint generated by default as identity primary key,
    email      varchar(255) not null unique,
    password   varchar(255) not null,
    nickname   varchar(255) not null,
    role       varchar(20)  not null,
    created_at timestamptz  not null,
    updated_at timestamptz  not null
);
