-- 알림(인앱). 제네릭 이벤트 로그: 폴리모픽 타겟(클라 라우팅용) + 비정규화 렌더필드.
-- 푸시(FCM)는 이 위 후처리. 저장소·읽음·폴링은 외부 의존 0.
create table notifications (
    id           bigint        generated by default as identity primary key,
    recipient_id bigint        not null references users (id) on delete cascade,  -- 받는 사람
    type         varchar(40)   not null,                        -- EPISODE_PUBLISHED/INQUIRY_ANSWERED ...
    target_type  varchar(20),                                   -- SERIES/EPISODE/INQUIRY/POST/COMMENT/USER (라우팅 분류)
    target_id    bigint,                                        -- 라우팅 식별자(FK 안 검)
    actor_id     bigint,                                        -- 유발자. null=시스템
    title        varchar(255)  not null,                        -- 비정규화 헤드라인
    message      varchar(500)  not null,                        -- 비정규화 본문
    read_at      timestamptz,                                   -- null=미읽음
    dedup_key    varchar(200),                                  -- 멱등키. null=중복 허용
    created_at   timestamptz   not null,
    updated_at   timestamptz   not null
);
-- 내 목록(최신순 페이징)
create index idx_notifications_recipient on notifications (recipient_id, id desc);
-- 미읽음 개수·집계(부분 인덱스)
create index idx_notifications_unread on notifications (recipient_id) where read_at is null;
-- 멱등 — 수신자 단위(다대상 fan-out에서 한 수신자가 다른 수신자 알림을 묵음시키지 않도록).
create unique index uq_notifications_dedup on notifications (recipient_id, dedup_key) where dedup_key is not null;
