-- 회차 댓글에 1-depth 대댓글(parent_id) + 댓글 좋아요(comment_likes) 추가.
-- 대댓글: parent_id가 최상위 댓글을 가리킨다(대댓글의 대댓글은 서비스에서 최상위로 평탄화).
alter table comments add column parent_id bigint references comments (id);
create index idx_comments_parent_id on comments (parent_id);

-- 댓글/대댓글 좋아요. user-comment 멱등(유니크) — episode_likes 구조를 복제한다.
create table comment_likes (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null references users (id),
    comment_id bigint      not null references comments (id),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_comment_like_user_comment unique (user_id, comment_id)
);

create index idx_comment_likes_comment_id on comment_likes (comment_id);
