-- 게시글 비추천 (D3 확정) — post_likes 구조 복제. 추천↔비추천 상호배타는 서비스가 강제한다.
create table post_dislikes (
    id         bigint      generated by default as identity primary key,
    user_id    bigint      not null references users (id) on delete cascade,
    post_id    bigint      not null references posts (id) on delete cascade,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_post_dislike unique (user_id, post_id)
);
create index idx_post_dislikes_post on post_dislikes (post_id);

alter table posts add column dislike_count int not null default 0;
