-- 게시글 댓글/대댓글 좋아요·싫어요 (D3 확정 — 회차 comment_likes V27 구조 복제, 싫어요 추가).
-- 게시글 삭제 → 댓글 cascade → 여기도 cascade로 정리. 좋아요↔싫어요 상호배타는 서비스가 강제한다.
create table post_comment_likes (
    id         bigint      generated by default as identity primary key,
    user_id    bigint      not null references users (id) on delete cascade,
    comment_id bigint      not null references post_comments (id) on delete cascade,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_post_comment_like unique (user_id, comment_id)
);
create index idx_post_comment_likes_comment on post_comment_likes (comment_id);

create table post_comment_dislikes (
    id         bigint      generated by default as identity primary key,
    user_id    bigint      not null references users (id) on delete cascade,
    comment_id bigint      not null references post_comments (id) on delete cascade,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_post_comment_dislike unique (user_id, comment_id)
);
create index idx_post_comment_dislikes_comment on post_comment_dislikes (comment_id);

alter table post_comments add column like_count    int not null default 0;
alter table post_comments add column dislike_count int not null default 0;
