create table refresh_tokens (
    id         bigint generated by default as identity primary key,
    token      varchar(255) not null unique,
    user_id    bigint       not null,
    expires_at timestamptz  not null,
    created_at timestamptz  not null,
    updated_at timestamptz  not null
);

create index idx_refresh_tokens_user_id on refresh_tokens (user_id);
