-- 채팅 코어 (CH2) — 폴링 MVP. 모델은 docs 5tab-design-review §채팅 합의 골격 + status만 가산.
-- DIRECT 대화의 DM 요청 수락/거절은 conversations.status로 흡수한다(친구=상호팔로우면 즉시 ACCEPTED).
-- role·client_msg_id는 골격만(GROUP·멱등 전송은 후속 슬라이스).

create table conversations (
    id         bigint      generated by default as identity primary key,
    type       varchar(10) not null,               -- DIRECT | GROUP
    status     varchar(10) not null,               -- PENDING | ACCEPTED | DECLINED (GROUP은 항상 ACCEPTED)
    title      varchar(100),                        -- GROUP 전용 표시명
    direct_key varchar(50) unique,                  -- 'minUserId:maxUserId' — DIRECT 중복 방지(동시 생성 경쟁 차단)
    created_by bigint      not null references users (id) on delete cascade,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create table conversation_members (
    id                   bigint      generated by default as identity primary key,
    conversation_id      bigint      not null references conversations (id) on delete cascade,
    user_id              bigint      not null references users (id) on delete cascade,
    role                 varchar(10),               -- 골격만(GROUP 방장 등 후속)
    last_read_message_id bigint,                    -- high-water-mark 읽음(null = 미열람)
    created_at           timestamptz not null,
    updated_at           timestamptz not null,
    constraint uq_conversation_member unique (conversation_id, user_id)
);
create index idx_conversation_members_user on conversation_members (user_id);

create table messages (
    id              bigint        generated by default as identity primary key,
    conversation_id bigint        not null references conversations (id) on delete cascade,
    sender_id       bigint        not null references users (id) on delete cascade,
    content         varchar(2000) not null,
    client_msg_id   varchar(64),                    -- 골격만(재전송 멱등 후속)
    created_at      timestamptz   not null,
    updated_at      timestamptz   not null
);
create index idx_messages_conversation_desc on messages (conversation_id, id desc);
