-- 사용자 차단 (CB, 확정 D7=a) — 효과: DM 생성/요청 양방향 차단 + 글·댓글 FE 숨김(BE 무필터).
create table user_blocks (
    id         bigint      generated by default as identity primary key,
    blocker_id bigint      not null references users (id) on delete cascade,
    blocked_id bigint      not null references users (id) on delete cascade,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_block_pair unique (blocker_id, blocked_id)
);
create index idx_user_blocks_blocker on user_blocks (blocker_id);
create index idx_user_blocks_blocked on user_blocks (blocked_id);
