-- 게시글 카테고리 등록제 (C7, 확정 D1=B) — enum→FK. name 자체가 표시 라벨(별도 라벨 매핑 없음).
-- created_by=null이면 시드(추천/자유/팬아트/질문), 값이 있으면 사용자 등록. 삭제 API 없음.
create table post_categories (
    id         bigint      generated by default as identity primary key,
    name       varchar(20) not null unique,
    created_by bigint      references users (id) on delete set null,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

insert into post_categories (name, created_by, created_at, updated_at) values
    ('추천', null, now(), now()),
    ('자유', null, now(), now()),
    ('팬아트', null, now(), now()),
    ('질문', null, now(), now());

update posts set category = '추천' where category = 'RECOMMEND';
update posts set category = '자유' where category = 'FREE';
update posts set category = '팬아트' where category = 'FANART';
update posts set category = '질문' where category = 'QUESTION';

alter table posts add constraint fk_posts_category foreign key (category) references post_categories (name);
