-- 창작자 온톨로지 계측 — append-only 열람 이벤트.
-- 기존 read_logs(uq(user_id, episode_id))와 목적이 다르다: read_logs는 "서재 열람 기록"
-- 사용자 기능이고, 이 테이블은 재열람·진도율·유입경로를 세는 분석용이다. 유니크 제약이 없다.
create table reading_events (
    id           bigint generated by default as identity primary key,
    occurred_at  timestamptz not null,
    user_id      bigint      null references users(id) on delete set null,
    series_id    bigint      not null references series(id) on delete cascade,
    episode_id   bigint      not null references episodes(id) on delete cascade,
    episode_no   int         not null,
    entry_point  varchar(20) not null,
    progress_pct smallint    not null,
    completed    boolean     not null,
    dwell_ms     integer     not null,
    session_id   uuid        not null
);

-- 일자 범위 집계(요약·유입경로)용
create index idx_reading_events_series_occurred on reading_events (series_id, occurred_at);
-- 회차별 잔존 곡선용
create index idx_reading_events_series_episode on reading_events (series_id, episode_no);
