-- 온톨로지 액션 감사 로그.
-- Foundry에서 감사 로그 없는 액션은 액션으로 치지 않는다(설계문서 §3-3).
--
-- 수신자 개인 id를 저장하지 않는다. 개인 참조 컬럼은 actor_id 하나뿐이고 규모는 정수로만 남긴다:
-- 이 프로젝트는 탈퇴가 soft delete라 FK on delete가 발화하지 않아, 개인 id를 남기면
-- 익명화 대상이 하나 늘고 탈퇴 경로를 함께 확장해야 한다. 애초에 남기지 않으면 그 축이 생기지 않는다.
-- 누구에게 갔는지는 notifications 테이블 자체가 이미 기록이다.
create table ontology_action_log (
    id              bigint      generated by default as identity primary key,
    occurred_at     timestamptz not null,
    actor_id        bigint      not null references users(id),
    action_type     varchar(40) not null,
    object_type     varchar(40) not null,
    object_id       bigint      not null,
    result          varchar(30) not null,
    recipient_count int         not null default 0
);

-- 주 1회 스로틀 판정: (대상 작품, 액션, EXECUTED, 최근순) 선조회 전용.
create index idx_ontology_action_log_scope
    on ontology_action_log (object_id, action_type, result, occurred_at desc);

-- 수신자 산출·겹침 계산이 user_id로 그룹핑한다. 기존 인덱스는 (series_id, *) 뿐이라 타지 못했다.
create index idx_reading_events_user on reading_events (user_id);
