create table series (
    id          bigint generated by default as identity primary key,
    title       varchar(255) not null,
    description text,
    author_id   bigint       not null references users (id),
    age_rating  varchar(20)  not null,
    status      varchar(20)  not null,
    created_at  timestamptz  not null,
    updated_at  timestamptz  not null
);

create index idx_series_author_id on series (author_id);

create table series_publish_days (
    series_id   bigint      not null references series (id),
    publish_day varchar(10) not null,
    primary key (series_id, publish_day)
);
