create table episodes (
    id          bigint generated by default as identity primary key,
    series_id   bigint       not null references series (id),
    episode_no  integer      not null,
    title       varchar(255) not null,
    status      varchar(20)  not null,
    publish_at  timestamptz,
    created_at  timestamptz  not null,
    updated_at  timestamptz  not null,
    constraint uq_episode_series_no unique (series_id, episode_no)
);

create index idx_episodes_series_id on episodes (series_id);

create table episode_images (
    id          bigint generated by default as identity primary key,
    episode_id  bigint       not null references episodes (id),
    sort_order  integer      not null,
    path        varchar(500) not null,
    width       integer      not null,
    height      integer      not null
);

create index idx_episode_images_episode_id on episode_images (episode_id);
