create table subscriptions (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null references users (id),
    series_id  bigint      not null references series (id),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_subscription_user_series unique (user_id, series_id)
);

create index idx_subscriptions_user_id on subscriptions (user_id);

create table read_logs (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null references users (id),
    episode_id bigint      not null references episodes (id),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_readlog_user_episode unique (user_id, episode_id)
);

create index idx_read_logs_user_id on read_logs (user_id);
