-- 회차 좋아요. user-episode 멱등(유니크) — read_logs 구조를 복제한다.
create table episode_likes (
    id         bigint generated by default as identity primary key,
    user_id    bigint      not null references users (id),
    episode_id bigint      not null references episodes (id),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uq_episode_like_user_episode unique (user_id, episode_id)
);

create index idx_episode_likes_episode_id on episode_likes (episode_id);
